# -*- coding: utf-8 -*-
{
    'name': "Clinic All",
    'summary': 'Hospital Management System for managing Hospital and medical facilities flows',
    'description': """ Hospital Management System for managing Clinics, Hospitals and medical facilities """,
    'author': "ENG.Remon Salem",
    'website': "http://www.github.com/remonSalem",
    'category': 'Clinic',
    'version': '17.0.0.0.1',
    'license': 'LGPL-3',
    # any module necessary for this one to work correctly
    'depends': [
        'ksc_clinic_base',
        'ksc_radiology',
        'ksc_laboratory',
        'ksc_dental',
        'ksc_dermatology',
        'ksc_general_practitioner',
        'ksc_internal_medicine',
        'ksc_nose_and_ear',
        'ksc_nutrition',
        'ksc_obstetrics_and_gynecology',
        'ksc_ophthalmology',
        'ksc_orthopedic',
        'ksc_pediatric',
        'ksc_physiotherapy',
        'ksc_urology',
        'ksc_rooster_type',
        'ksc_prescription_model',
        'sequence_reset_period',
    ],
}
