# -*- coding: utf-8 -*-
{
    'name': 'Laboratory Management',
    'summary': 'Manage Lab requests, Lab tests, Invoicing and related history for hospital.',
    'description': """
        This module add functionality to manage Laboratory flow. laboratory management system
        Hospital Management lab tests laboratory invoices laboratory test results 
    """,
    'author': "ENG.Remon Salem",
    'website': "http://www.github.com/remonSalem",
    'category': 'Clinic',
    'version': '17.0.0.0.1',
    'depends': ['stock', 'ksc_clinic_base', 'ksc_prescription_model', 'ksc_patient_report'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'report/barcodelabels.xml',
        'report/report_component.xml',
        'report/lab_result_report.xml',
        'report/lab_request_report.xml',
        # 'data/mail_template.xml',
        'data/laboratory_data.xml',
        # 'data/lab_uom_data.xml',
        'data/lab_sample_type_data.xml',
        'views/lab_uom_view.xml',
        'views/laboratory_request_view.xml',
        'views/laboratory_view.xml',
        'views/laboratory_test_view.xml',
        'views/laboratory_sample_view.xml',
        'views/hms_base_view.xml',
        'views/res_config.xml',
        'views/templates_view.xml',
        'views/parameter.xml',
        'views/menu_item.xml',
        'report/barcodelabels.xml',
        'wizard/barcode_wizard.xml',
    ],
    'installable': True,
    'application': True,
}
